#!/usr/bin/env bash
set -Eeuo pipefail
CONFIRM="${RAM26_NATIVE_ALLIN_CONFIRM:-}"
if [[ "$CONFIRM" != "YES_NATIVE_BRIDGE_FIX_ALL_GATES_AND_FULL_LIVE" ]]; then
  echo "RAM26_NATIVE_ALLIN_CONFIRM must be YES_NATIVE_BRIDGE_FIX_ALL_GATES_AND_FULL_LIVE"
  exit 2
fi
KIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RAM26_BRIDGE_V2_INSTALL_CONFIRM=YES_INSTALL_RAM26_NATIVE_BRIDGE_V2 bash "$KIT_DIR/01_install_ram26_native_bridge_v2.sh"
RAM26_BRIDGE_V2_STAGE_CONFIRM=YES_RUN_RAM26_BRIDGE_V2_STAGE bash "$KIT_DIR/02_run_bridge_v2_stage.sh"
RAM26_PATCH_G8_CONFIRM=YES_PATCH_G8_BRIDGE_ALIAS bash "$KIT_DIR/03_patch_g8_bridge_alias.sh"
RAM26_BRIDGE_V2_PROMOTE_CONFIRM=YES_PROMOTE_RAM26_BRIDGE_V2_CURRENT bash "$KIT_DIR/04_promote_bridge_v2_current.sh"
RAM26_ALL_GATES_NATIVE_VERIFY_CONFIRM=YES_VERIFY_NATIVE_BRIDGE_ALL_GATES bash "$KIT_DIR/05_verify_native_all_gates.sh"
RAM26_NATIVE_FULL_LIVE_CONFIRM=YES_NATIVE_BRIDGE_ALL_GATES_FULL_LIVE bash "$KIT_DIR/06_native_full_live_go.sh"
RAM26_NATIVE_MONITOR_CONFIRM=YES_MONITOR_NATIVE_BRIDGE_FULL_LIVE DURATION_SEC="${DURATION_SEC:-1800}" INTERVAL_SEC=30 bash "$KIT_DIR/07_native_post_live_monitor.sh"
echo "RAM26_NATIVE_BRIDGE_ALL_GATES_FULL_LIVE_SEQUENCE_COMPLETE"
