#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
autogen_p0_overlay_bundle.py
- ARESX extreme_2 엔진에 P0 오버레이(실행모듈 5개 + 계측) 스캐폴딩 자동 생성
- 엔진 파일 hook 자동 패치 시도(안전 우선: 실패하면 스니펫/가이드 생성)

사용 예)
  python autogen_p0_overlay_bundle.py \
    --aub-root /home/ubuntu/AUB \
    --engine /home/ubuntu/AUB/baseline/ares_phase2b_v661_addon_engine_v3_integration.py
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

TEMPLATE_HEADER = "# Auto-generated by autogen_p0_overlay_bundle.py\n"


def write_text(path: Path, content: str, overwrite: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not overwrite:
        return
    path.write_text(content, encoding="utf-8")


def backup_file(path: Path) -> Path:
    ts = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup = path.with_suffix(path.suffix + f".bak_{ts}")
    backup.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    return backup


def try_patch_engine(engine_path: Path, import_line: str, hook_snippet: str) -> Tuple[bool, str]:
    """
    매우 보수적인 자동 패치:
    - import 삽입: 최상단 import 블록 근처(첫 def/class 전)
    - hook 삽입: 'return ...weights...' 형태를 찾으면 직전에 weights = apply_overlays(...)
    실패하면 False + 메시지 반환
    """
    src = engine_path.read_text(encoding="utf-8").splitlines(True)

    # 1) import 삽입 위치: 첫 def/class 직전, 또는 마지막 import 라인 다음
    first_def_idx = None
    last_import_idx = None
    for i, line in enumerate(src):
        if re.match(r"^\s*(def|class)\s+", line):
            first_def_idx = i
            break
        if re.match(r"^\s*(import|from)\s+", line):
            last_import_idx = i

    insert_import_at = None
    if last_import_idx is not None:
        insert_import_at = last_import_idx + 1
    elif first_def_idx is not None:
        insert_import_at = first_def_idx
    else:
        insert_import_at = 0

    # 이미 import가 있으면 중복 삽입 금지
    if any(import_line.strip() in l for l in src):
        imported = True
    else:
        imported = False
        src.insert(insert_import_at, import_line + "\n")

    # 2) hook 삽입: return weights 패턴 탐색
    #    (너무 공격적으로 여러 곳을 바꾸지 않기 위해 "첫 번째 적합 지점 1회만" 적용)
    return_idx = None
    return_var = None
    for i, line in enumerate(src):
        m = re.search(r"return\s+([A-Za-z_][A-Za-z0-9_]*)", line)
        if not m:
            continue
        var = m.group(1)
        if "weight" in var.lower():
            return_idx = i
            return_var = var
            break

    if return_idx is None or return_var is None:
        msg = "엔진에서 'return <...weights...>' 패턴을 못 찾음(자동 패치 보류). patches/ 스니펫을 수동으로 적용하세요."
        return (False, msg)

    # hook line 생성 (returns_history/vix/current_return/timestamp 변수명은 엔진에 따라 다를 수 있음)
    hook_lines = []
    hook_lines.append("\n    # === P0 OVERLAY HOOK (auto) ===\n")
    hook_lines.append(
        f"    {return_var}, _p0_dbg = apply_p0_overlays(\n"
        f"        {return_var},\n"
        f"        returns_history=locals().get('returns_history'),\n"
        f"        vix=locals().get('vix'),\n"
        f"        current_return=locals().get('current_return'),\n"
        f"        timestamp=locals().get('timestamp') or locals().get('date') or None,\n"
        f"    )\n"
    )
    hook_lines.append("    # ==============================\n\n")

    # return 직전에 삽입(들여쓰기 맞춤은 'return' 라인 들여쓰기 기준으로)
    indent = re.match(r"^(\s*)", src[return_idx]).group(1)
    hook_lines = [indent + hl if hl.strip() else hl for hl in hook_lines]
    src[return_idx:return_idx] = hook_lines

    # helper 함수가 이미 있으면 스킵
    if "def apply_p0_overlays(" not in "".join(src):
        src.append("\n\n" + hook_snippet + "\n")

    engine_path.write_text("".join(src), encoding="utf-8")
    return (True, f"자동 패치 성공(import inserted={not imported}, hook at line={return_idx}).")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--aub-root", required=True, help="예: /home/ubuntu/AUB")
    ap.add_argument("--engine", required=True, help="엔진 파일 경로")
    ap.add_argument("--overwrite", action="store_true", help="기존 생성 파일 덮어쓰기")
    args = ap.parse_args()

    aub_root = Path(args.aub_root).resolve()
    engine_path = Path(args.engine).resolve()
    overwrite = bool(args.overwrite)

    # 경로
    prod_modules = aub_root / "production_modules"
    overlays_dir = prod_modules / "overlays"
    adapters_dir = overlays_dir / "adapters"
    scripts_dir = aub_root / "scripts"
    configs_dir = aub_root / "configs"
    patches_dir = aub_root / "patches"

    # 0) README
    write_text(
        overlays_dir / "README_P0_OVERLAYS.md",
        TEMPLATE_HEADER + """# P0 Overlays (Exec-only 5 modules)

대상 실행 모듈(Top20 #1~3, #6~7):
- market_guard_ml9.py
- regime_detector.py
- risk_manager.py
- volatility_targeting.py
- dynamic_no_trade_band.py

계측(병렬):
- pypbo (PBO/DSR)
- tcapy (TCA/비용)

통합 원칙:
- extreme_2 파라미터 수정 금지
- 모듈은 1개씩 순차 통합/검증
- 최근/최악 레짐(2018-2021, 2022+) 우선

검증 게이트:
- 2018-2021 OOS Sharpe > 1.5
- DSR > 5%
- Max Drawdown < 25%
- Turnover < 50%/year
""",
        overwrite=overwrite,
    )

    # 1) __init__.py
    write_text(overlays_dir / "__init__.py", TEMPLATE_HEADER + "", overwrite=overwrite)
    write_text(adapters_dir / "__init__.py", TEMPLATE_HEADER + "", overwrite=overwrite)

    # 2) Config YAML
    write_text(
        configs_dir / "p0_overlays.yaml",
        TEMPLATE_HEADER + """# P0 overlay config
enabled: true

# 실행 순서(기본): no-trade -> vol targeting -> risk -> regime -> market guard(kill switch)
order:
  - dynamic_no_trade_band
  - volatility_targeting
  - risk_manager
  - regime_detector
  - market_guard_ml9

modules:
  dynamic_no_trade_band:
    enabled: true
    params:
      band_bps: 5
      min_trade_weight: 0.001

  volatility_targeting:
    enabled: true
    params:
      target_vol: 0.15
      lookback: 20
      floor: 0.2
      cap: 1.0

  risk_manager:
    enabled: true
    params:
      cvar_alpha: 0.05

  regime_detector:
    enabled: true
    params:
      n_states: 4
      lookback: 252

  market_guard_ml9:
    enabled: true
    params:
      crash_sigma: 4.0

trace:
  enabled: true
  path: "logs/p0_overlay_trace.csv"
""",
        overwrite=overwrite,
    )

    # 3) Pipeline
    write_text(
        overlays_dir / "p0_pipeline.py",
        TEMPLATE_HEADER + r'''
from __future__ import annotations

import csv
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import yaml


@dataclass
class OverlayContext:
    """파이프라인 전체에서 공유되는 컨텍스트"""
    returns_history: Optional[np.ndarray] = None
    vix: Optional[float] = None
    current_return: Optional[float] = None
    timestamp: Optional[Any] = None
    extra: Optional[Dict[str, Any]] = None


@dataclass
class OverlayResult:
    """각 모듈의 출력"""
    module_name: str
    weights_out: np.ndarray
    scalar: float  # gross_exposure_out / gross_exposure_in (0~1 권장)
    trigger: bool  # 모듈이 실질적으로 개입했는지
    info: Dict[str, Any] = field(default_factory=dict)


def safe_scalar(w_in: np.ndarray, w_out: np.ndarray) -> float:
    """gross exposure 비율로 scalar 계산"""
    g_in = float(np.sum(np.abs(w_in)))
    g_out = float(np.sum(np.abs(w_out)))
    if g_in < 1e-12:
        return 1.0
    return float(g_out / g_in)


class OverlayPipeline:
    """
    오버레이 파이프라인
    - 각 모듈을 순차 적용
    - trace 로깅 지원
    """
    def __init__(self, modules: List[Tuple[str, Any]], trace_path: Optional[str] = None):
        self.modules = modules  # [(name, adapter_instance), ...]
        self.trace_path = trace_path
        self._trace_initialized = False

    def apply(self, weights: np.ndarray, ctx: OverlayContext) -> Tuple[np.ndarray, List[OverlayResult]]:
        w = np.asarray(weights, dtype=float).copy()
        results: List[OverlayResult] = []

        for name, adapter in self.modules:
            try:
                res: OverlayResult = adapter.apply(ctx, w)
                w = res.weights_out
                results.append(res)
            except Exception as e:
                # 모듈 실패 시 패스스루
                results.append(OverlayResult(name, w, 1.0, False, {"error": str(e)}))

        # trace 로깅
        if self.trace_path:
            self._log_trace(ctx, results)

        return w, results

    def _log_trace(self, ctx: OverlayContext, results: List[OverlayResult]) -> None:
        path = Path(self.trace_path)
        path.parent.mkdir(parents=True, exist_ok=True)

        row = {"timestamp": ctx.timestamp, "vix": ctx.vix, "current_return": ctx.current_return}
        for res in results:
            row[f"{res.module_name}_scalar"] = res.scalar
            row[f"{res.module_name}_trigger"] = int(res.trigger)

        write_header = not path.exists() or not self._trace_initialized
        with open(path, "a", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=list(row.keys()))
            if write_header:
                writer.writeheader()
                self._trace_initialized = True
            writer.writerow(row)


def build_pipeline_from_yaml(cfg_path: str) -> OverlayPipeline:
    """YAML 설정에서 파이프라인 빌드"""
    with open(cfg_path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    if not cfg.get("enabled", True):
        # 비활성화 시 빈 파이프라인
        return OverlayPipeline([], None)

    order = cfg.get("order", [])
    modules_cfg = cfg.get("modules", {})
    trace_cfg = cfg.get("trace", {})
    trace_path = trace_cfg.get("path") if trace_cfg.get("enabled") else None

    # 어댑터 동적 로드
    from .adapters.dynamic_no_trade_band_adapter import DynamicNoTradeBandAdapter
    from .adapters.volatility_targeting_adapter import VolatilityTargetingAdapter
    from .adapters.risk_manager_adapter import RiskManagerAdapter
    from .adapters.regime_detector_adapter import RegimeDetectorAdapter
    from .adapters.market_guard_ml9_adapter import MarketGuardML9Adapter

    adapter_map = {
        "dynamic_no_trade_band": DynamicNoTradeBandAdapter,
        "volatility_targeting": VolatilityTargetingAdapter,
        "risk_manager": RiskManagerAdapter,
        "regime_detector": RegimeDetectorAdapter,
        "market_guard_ml9": MarketGuardML9Adapter,
    }

    modules = []
    for name in order:
        mod_cfg = modules_cfg.get(name, {})
        if not mod_cfg.get("enabled", True):
            continue
        adapter_cls = adapter_map.get(name)
        if adapter_cls:
            adapter = adapter_cls(mod_cfg)
            modules.append((name, adapter))

    return OverlayPipeline(modules, trace_path)
''',
        overwrite=overwrite,
    )

    # 4) Adapters (stubs)
    adapter_stub = TEMPLATE_HEADER + r'''
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional, Tuple

import numpy as np

from ..p0_pipeline import OverlayContext, OverlayResult, safe_scalar


class BaseAdapter:
    def __init__(self, cfg: Dict[str, Any]):
        # cfg는 {"enabled": bool, "params": {...}} 형태를 기대
        self.cfg = cfg or {}
        self.params = dict(self.cfg.get("params", {}))

    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        raise NotImplementedError
'''

    write_text(adapters_dir / "_base.py", adapter_stub, overwrite=overwrite)

    # 각 어댑터 템플릿
    write_text(
        adapters_dir / "dynamic_no_trade_band_adapter.py",
        TEMPLATE_HEADER + r'''
from __future__ import annotations

from typing import Any, Dict

import numpy as np

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult, safe_scalar


class DynamicNoTradeBandAdapter(BaseAdapter):
    """
    목표: dynamic_no_trade_band.py를 호출해 작은 변화는 거래하지 않도록 weights를 정리
    TODO: 실제 dynamic_no_trade_band.py의 함수/클래스 인터페이스에 맞춰 연결
    """
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()

        # ===== TODO: 실제 모듈 연결부 =====
        band_bps = float(self.params.get("band_bps", 5))
        min_trade_weight = float(self.params.get("min_trade_weight", 0.001))
        # 간이 no-trade band (placeholder): 절대값이 min_trade_weight 미만이면 0
        w_out[np.abs(w_out) < min_trade_weight] = 0.0
        # =================================

        scalar = safe_scalar(w_in, w_out)
        trigger = bool(np.any(np.abs(w_in - w_out) > 0))
        info: Dict[str, Any] = {"band_bps": band_bps, "min_trade_weight": min_trade_weight}
        return OverlayResult("dynamic_no_trade_band", w_out, scalar, trigger, info)
''',
        overwrite=overwrite,
    )

    write_text(
        adapters_dir / "volatility_targeting_adapter.py",
        TEMPLATE_HEADER + r'''
from __future__ import annotations

from typing import Any, Dict, Optional

import numpy as np

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult


class VolatilityTargetingAdapter(BaseAdapter):
    """
    목표: volatility_targeting.py가 산출한 scalar로 weights 스케일
    TODO: 실제 모듈 연결
    """
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()

        target_vol = float(self.params.get("target_vol", 0.15))
        lookback = int(self.params.get("lookback", 20))
        floor = float(self.params.get("floor", 0.2))
        cap = float(self.params.get("cap", 1.0))

        # ===== TODO: 실제 모듈 연결부 =====
        r = ctx.returns_history
        if r is None or len(r) < max(5, lookback):
            scalar = 1.0
        else:
            recent = np.asarray(r[-lookback:], dtype=float)
            vol = float(np.std(recent) * np.sqrt(252))
            if vol <= 0:
                scalar = 1.0
            else:
                scalar = target_vol / vol
        scalar = float(np.clip(scalar, floor, cap))
        # =================================

        w_out = w_in * scalar
        trigger = bool(scalar < 0.999)
        info: Dict[str, Any] = {"target_vol": target_vol, "lookback": lookback, "floor": floor, "cap": cap, "scalar": scalar}
        return OverlayResult("volatility_targeting", w_out, scalar, trigger, info)
''',
        overwrite=overwrite,
    )

    write_text(
        adapters_dir / "risk_manager_adapter.py",
        TEMPLATE_HEADER + r'''
from __future__ import annotations

from typing import Any, Dict

import numpy as np

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult, safe_scalar


class RiskManagerAdapter(BaseAdapter):
    """
    목표: risk_manager.py(CVaR 등)로 weights를 리스크 제약에 맞게 수정
    TODO: 실제 risk_manager.py 연결
    """
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()

        cvar_alpha = float(self.params.get("cvar_alpha", 0.05))

        # ===== TODO: 실제 모듈 연결부 =====
        # placeholder: gross exposure cap 1.0로 정규화(리스크 오버레이 느낌만)
        gross = float(np.sum(np.abs(w_out)))
        if gross > 1.0 and gross > 0:
            w_out = w_out / gross
        # =================================

        scalar = safe_scalar(w_in, w_out)
        trigger = bool(scalar < 0.999)
        info: Dict[str, Any] = {"cvar_alpha": cvar_alpha}
        return OverlayResult("risk_manager", w_out, scalar, trigger, info)
''',
        overwrite=overwrite,
    )

    write_text(
        adapters_dir / "regime_detector_adapter.py",
        TEMPLATE_HEADER + r'''
from __future__ import annotations

from typing import Any, Dict

import numpy as np

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult


class RegimeDetectorAdapter(BaseAdapter):
    """
    목표: regime_detector.py가 레짐을 산출하고, 레짐에 따라 scalar(또는 weights 수정)를 적용
    TODO: 실제 regime_detector.py(HMM) 연결
    """
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)

        n_states = int(self.params.get("n_states", 4))
        lookback = int(self.params.get("lookback", 252))

        # ===== TODO: 실제 모듈 연결부 =====
        # placeholder: VIX가 높으면 보수적으로 scalar 축소
        vix = ctx.vix
        if vix is None:
            scalar = 1.0
            regime = "UNKNOWN"
        else:
            if vix >= 35:
                scalar, regime = 0.1, "CRISIS"
            elif vix >= 25:
                scalar, regime = 0.3, "HIGH_VOL"
            elif vix >= 20:
                scalar, regime = 0.7, "NORMAL"
            else:
                scalar, regime = 1.0, "LOW_VOL"
        # =================================

        w_out = w_in * float(scalar)
        trigger = bool(float(scalar) < 0.999)
        info: Dict[str, Any] = {"n_states": n_states, "lookback": lookback, "regime": regime, "scalar": float(scalar)}
        return OverlayResult("regime_detector", w_out, float(scalar), trigger, info)
''',
        overwrite=overwrite,
    )

    write_text(
        adapters_dir / "market_guard_ml9_adapter.py",
        TEMPLATE_HEADER + r'''
from __future__ import annotations

from typing import Any, Dict

import numpy as np

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult


class MarketGuardML9Adapter(BaseAdapter):
    """
    목표: market_guard_ml9.py의 crash 감지 결과로 kill-switch(강제 현금화) 적용
    TODO: 실제 market_guard_ml9.py 연결
    """
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()

        crash_sigma = float(self.params.get("crash_sigma", 4.0))

        # ===== TODO: 실제 모듈 연결부 =====
        # placeholder: 당일 수익률이 특정 임계 이하이면 전부 0 (kill)
        r = ctx.current_return
        crash = False
        if r is not None and r < -0.05:  # 임시 룰
            crash = True
            w_out[:] = 0.0
        # =================================

        scalar = 0.0 if crash else 1.0
        trigger = bool(crash)
        info: Dict[str, Any] = {"crash_sigma": crash_sigma, "crash": crash}
        return OverlayResult("market_guard_ml9", w_out, float(scalar), trigger, info)
''',
        overwrite=overwrite,
    )

    # 5) Overlap report script
    write_text(
        scripts_dir / "p0_overlap_report.py",
        TEMPLATE_HEADER + r'''
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


def jaccard(a: np.ndarray, b: np.ndarray) -> float:
    a = a.astype(bool)
    b = b.astype(bool)
    inter = np.sum(a & b)
    union = np.sum(a | b)
    return float(inter / union) if union > 0 else 0.0


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--trace", required=True, help="p0_overlay_trace.csv 경로")
    ap.add_argument("--out", default="REPORT_OVERLAP_P0.md")
    args = ap.parse_args()

    df = pd.read_csv(args.trace)
    # 모듈 이름 자동 추출
    trig_cols = [c for c in df.columns if c.endswith("_trigger")]
    mod_names = [c.replace("_trigger", "") for c in trig_cols]

    rows = []
    for i in range(len(mod_names)):
        for j in range(i + 1, len(mod_names)):
            a = df[f"{mod_names[i]}_trigger"].fillna(0).values
            b = df[f"{mod_names[j]}_trigger"].fillna(0).values

            # scalar corr
            si = df.get(f"{mod_names[i]}_scalar")
            sj = df.get(f"{mod_names[j]}_scalar")
            if si is not None and sj is not None:
                x = si.fillna(1.0).values
                y = sj.fillna(1.0).values
                corr = float(np.corrcoef(x, y)[0, 1]) if (np.std(x) > 1e-12 and np.std(y) > 1e-12) else 0.0
            else:
                corr = 0.0

            joint = float(np.mean((a.astype(bool) & b.astype(bool))))
            jac = jaccard(a, b)

            rows.append({
                "i": mod_names[i],
                "j": mod_names[j],
                "corr_scalar": corr,
                "joint_trigger_rate": joint,
                "jaccard": jac,
                "redundant_warn": "YES" if jac >= 0.8 else "",
            })

    out_df = pd.DataFrame(rows).sort_values(["jaccard", "joint_trigger_rate"], ascending=False)

    md = []
    md.append("# P0 Overlay Overlap Report\n")
    md.append(f"- trace: `{args.trace}`\n")
    md.append("\n## Pairwise overlap (trigger)\n\n")
    md.append(out_df.to_markdown(index=False))
    md.append("\n\n## Notes\n- Jaccard >= 0.8 는 중복 가능성 경고\n")

    Path(args.out).write_text("\n".join(md), encoding="utf-8")
    print(f"[OK] wrote {args.out}")


if __name__ == "__main__":
    main()
''',
        overwrite=overwrite,
    )

    # 6) Eval matrix script
    write_text(
        scripts_dir / "p0_eval_matrix.py",
        TEMPLATE_HEADER + r'''
#!/usr/bin/env python3
"""
P0 Overlay Evaluation Matrix
- 모듈 1개씩 순차 통합하며 백테스트 실행
- 검증 게이트 확인 (2018-2021 Sharpe > 1.5, DSR > 5%, MaxDD < 25%, Turnover < 50%)
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Any

import yaml


def run_backtest(engine_path: str, config_path: str, enabled_modules: List[str]) -> Dict[str, Any]:
    """
    백테스트 실행 (placeholder)
    실제 구현 시 엔진 호출 및 결과 파싱
    """
    # TODO: 실제 백테스트 커맨드로 교체
    # 예: subprocess.run([...])
    
    # placeholder 결과
    return {
        "sharpe_mean": 1.95,
        "sharpe_2018_2021": 1.52,
        "sharpe_2022_plus": 1.88,
        "dsr": 0.06,
        "max_dd": 0.22,
        "turnover": 0.45,
    }


def check_gate(result: Dict[str, Any]) -> Dict[str, bool]:
    """검증 게이트 확인"""
    return {
        "sharpe_2018_2021_pass": result.get("sharpe_2018_2021", 0) > 1.5,
        "dsr_pass": result.get("dsr", 0) > 0.05,
        "max_dd_pass": result.get("max_dd", 1) < 0.25,
        "turnover_pass": result.get("turnover", 1) < 0.50,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="/home/ubuntu/AUB/configs/p0_overlays.yaml")
    ap.add_argument("--engine", default="/home/ubuntu/AUB/baseline/ares_phase2b_v661_addon_engine_v3_integration.py")
    ap.add_argument("--out", default="REPORT_P0_EVAL_MATRIX.md")
    args = ap.parse_args()

    # 설정 로드
    with open(args.config, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    order = cfg.get("order", [])
    
    # 단계별 실행
    results = []
    
    # Step 0: Baseline (모든 모듈 OFF)
    print("[Step 0] Baseline (all modules OFF)")
    baseline_result = run_backtest(args.engine, args.config, [])
    baseline_result["step"] = "baseline"
    baseline_result["modules"] = []
    baseline_result["gate"] = check_gate(baseline_result)
    results.append(baseline_result)
    
    # Step 1~N: 모듈 1개씩 추가
    enabled = []
    for i, mod in enumerate(order):
        enabled.append(mod)
        print(f"[Step {i+1}] Adding: {mod}")
        result = run_backtest(args.engine, args.config, enabled.copy())
        result["step"] = f"step_{i+1}"
        result["modules"] = enabled.copy()
        result["gate"] = check_gate(result)
        results.append(result)
    
    # 결과 출력
    md = []
    md.append("# P0 Overlay Evaluation Matrix\n")
    md.append("\n## Step-by-Step Results\n\n")
    md.append("| Step | Modules | Sharpe Mean | Sharpe 2018-2021 | DSR | MaxDD | Turnover | Gate |\n")
    md.append("|------|---------|-------------|------------------|-----|-------|----------|------|\n")
    
    for r in results:
        modules_str = ", ".join(r["modules"]) if r["modules"] else "baseline"
        gate_pass = all(r["gate"].values())
        gate_str = "✅ PASS" if gate_pass else "❌ FAIL"
        md.append(f"| {r['step']} | {modules_str} | {r['sharpe_mean']:.3f} | {r['sharpe_2018_2021']:.3f} | {r['dsr']:.1%} | {r['max_dd']:.1%} | {r['turnover']:.1%} | {gate_str} |\n")
    
    md.append("\n## Gate Criteria\n")
    md.append("- 2018-2021 OOS Sharpe > 1.5\n")
    md.append("- DSR > 5%\n")
    md.append("- Max Drawdown < 25%\n")
    md.append("- Turnover < 50%/year\n")
    
    Path(args.out).write_text("".join(md), encoding="utf-8")
    print(f"[OK] wrote {args.out}")


if __name__ == "__main__":
    main()
''',
        overwrite=overwrite,
    )

    # 7) Patch snippet + attempt patch
    import_line = "from production_modules.overlays.p0_pipeline import build_pipeline_from_yaml, OverlayContext"
    hook_snippet = r'''
# === P0 OVERLAY HELPERS (auto-generated) ===
import os
import numpy as np

_P0_PIPELINE = None

def apply_p0_overlays(weights, returns_history=None, vix=None, current_return=None, timestamp=None):
    """
    엔진에서 final weights 산출 직전에 호출.
    returns_history/vix/current_return 변수명이 엔진마다 다르면 hook 라인에서 locals().get(...)로 주입.
    """
    global _P0_PIPELINE
    cfg_path = os.getenv("AUB_P0_OVERLAY_CFG", "/home/ubuntu/AUB/configs/p0_overlays.yaml")
    if _P0_PIPELINE is None:
        _P0_PIPELINE = build_pipeline_from_yaml(cfg_path)

    ctx = OverlayContext(
        returns_history=np.asarray(returns_history) if returns_history is not None else None,
        vix=vix,
        current_return=current_return,
        timestamp=timestamp,
        extra=None,
    )
    w = np.asarray(weights, dtype=float)
    w2, dbg = _P0_PIPELINE.apply(w, ctx)
    return w2, dbg
# ==========================================
'''

    write_text(
        patches_dir / "ENGINE_HOOK_SNIPPET.py",
        TEMPLATE_HEADER + hook_snippet,
        overwrite=True,
    )

    write_text(
        patches_dir / "ENGINE_HOOK_GUIDE.md",
        TEMPLATE_HEADER + f"""# Engine Hook Guide (P0 overlays)

자동 패치가 실패하면 아래 순서로 수동 적용:

1) 엔진 파일 상단 import 영역에 추가:
```python
{import_line}
```

2) 엔진에서 final weights 반환 직전에 hook 삽입(변수명은 엔진에 맞게):
```python
weights, _p0_dbg = apply_p0_overlays(
    weights,
    returns_history=returns_history,
    vix=vix,
    current_return=current_return,
    timestamp=timestamp,
)
```

3) 엔진 파일 하단에 patches/ENGINE_HOOK_SNIPPET.py 내용을 붙여넣기.

환경변수:
- AUB_P0_OVERLAY_CFG=/home/ubuntu/AUB/configs/p0_overlays.yaml
""",
        overwrite=True,
    )

    # 패치 시도
    if engine_path.exists():
        backup = backup_file(engine_path)
        ok, msg = try_patch_engine(engine_path, import_line, hook_snippet)
        status = "SUCCESS" if ok else "SKIP"
        write_text(
            patches_dir / "PATCH_RESULT.txt",
            TEMPLATE_HEADER + f"{status}: {msg}\nbackup: {backup}\nengine: {engine_path}\n",
            overwrite=True,
        )
        print(f"[{status}] {msg}")
        print(f"backup: {backup}")
    else:
        print(f"[WARN] engine not found: {engine_path}")

    print("[OK] scaffold generated:")
    print(f"- {overlays_dir}")
    print(f"- {configs_dir / 'p0_overlays.yaml'}")
    print(f"- {scripts_dir / 'p0_overlap_report.py'}")
    print(f"- {scripts_dir / 'p0_eval_matrix.py'}")
    print(f"- {patches_dir}")


if __name__ == "__main__":
    main()
