#!/usr/bin/env python3
"""
connect_adapters_to_modules.py
==============================
어댑터 5개의 TODO 구간을 실제 모듈과 연결
"""

from pathlib import Path

ADAPTERS_DIR = Path("/home/ubuntu/AUB/production_modules/overlays/adapters")

# 1. dynamic_no_trade_band_adapter.py
DYNAMIC_NO_TRADE_BAND_ADAPTER = '''# Auto-generated by autogen_p0_overlay_bundle.py

from __future__ import annotations

import sys
from typing import Any, Dict

import numpy as np

# 실제 모듈 경로 추가
sys.path.insert(0, "/home/ubuntu/AUB/baseline")

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult, safe_scalar


class DynamicNoTradeBandAdapter(BaseAdapter):
    """
    Dynamic No-Trade Band Adapter
    실제 모듈: /home/ubuntu/AUB/baseline/dynamic_no_trade_band.py
    """
    
    def __init__(self, cfg: Dict[str, Any]):
        super().__init__(cfg)
        self._module = None
        self._initialized = False
    
    def _init_module(self):
        if self._initialized:
            return
        try:
            from dynamic_no_trade_band import DynamicNoTradeBand, DynamicBandConfig
            
            config = DynamicBandConfig(
                base_band=float(self.params.get("base_band", 0.015)),
                min_band=float(self.params.get("min_band", 0.008)),
                max_band=float(self.params.get("max_band", 0.05)),
            )
            self._module = DynamicNoTradeBand(config)
            self._initialized = True
        except Exception as e:
            print(f"[WARN] DynamicNoTradeBand init failed: {e}")
            self._module = None
            self._initialized = True
    
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()
        
        self._init_module()
        
        band_bps = float(self.params.get("band_bps", 5))
        min_trade_weight = float(self.params.get("min_trade_weight", 0.001))
        
        if self._module is not None and ctx.vix is not None:
            try:
                # 실제 모듈 호출
                band, diag = self._module.calculate_band(ctx.vix, str(ctx.timestamp))
                min_trade_weight = band  # 동적 밴드 적용
            except Exception as e:
                print(f"[WARN] DynamicNoTradeBand.calculate_band failed: {e}")
        
        # No-trade band 적용: 절대값이 min_trade_weight 미만이면 0
        w_out[np.abs(w_out) < min_trade_weight] = 0.0
        
        scalar = safe_scalar(w_in, w_out)
        trigger = bool(np.any(np.abs(w_in - w_out) > 0))
        info: Dict[str, Any] = {"band_bps": band_bps, "min_trade_weight": min_trade_weight}
        return OverlayResult("dynamic_no_trade_band", w_out, scalar, trigger, info)
'''

# 2. volatility_targeting_adapter.py
VOLATILITY_TARGETING_ADAPTER = '''# Auto-generated by autogen_p0_overlay_bundle.py

from __future__ import annotations

import sys
from typing import Any, Dict, Optional

import numpy as np

sys.path.insert(0, "/home/ubuntu/AUB/baseline")

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult


class VolatilityTargetingAdapter(BaseAdapter):
    """
    Volatility Targeting Adapter
    실제 모듈: /home/ubuntu/AUB/baseline/volatility_targeting.py
    """
    
    def __init__(self, cfg: Dict[str, Any]):
        super().__init__(cfg)
        self._module = None
        self._initialized = False
    
    def _init_module(self):
        if self._initialized:
            return
        try:
            from volatility_targeting import VolatilityTargeting, VolTargetConfig
            
            config = VolTargetConfig(
                target_vol=float(self.params.get("target_vol", 0.15)),
                vol_window=int(self.params.get("lookback", 20)),
                min_scale=float(self.params.get("floor", 0.2)),
                max_scale=float(self.params.get("cap", 2.0)),
            )
            self._module = VolatilityTargeting(config)
            self._initialized = True
        except Exception as e:
            print(f"[WARN] VolatilityTargeting init failed: {e}")
            self._module = None
            self._initialized = True
    
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()
        
        self._init_module()
        
        target_vol = float(self.params.get("target_vol", 0.15))
        lookback = int(self.params.get("lookback", 20))
        floor = float(self.params.get("floor", 0.2))
        cap = float(self.params.get("cap", 2.0))
        
        scalar = 1.0
        
        if self._module is not None and ctx.current_return is not None:
            try:
                # 실제 모듈 호출
                scalar, diag = self._module.calculate_scale(ctx.current_return, str(ctx.timestamp))
            except Exception as e:
                print(f"[WARN] VolatilityTargeting.calculate_scale failed: {e}")
                # Fallback: 간이 계산
                r = ctx.returns_history
                if r is not None and len(r) >= max(5, lookback):
                    recent = np.asarray(r[-lookback:], dtype=float)
                    vol = float(np.std(recent) * np.sqrt(252))
                    if vol > 0:
                        scalar = target_vol / vol
                    scalar = float(np.clip(scalar, floor, cap))
        else:
            # Fallback: 간이 계산
            r = ctx.returns_history
            if r is not None and len(r) >= max(5, lookback):
                recent = np.asarray(r[-lookback:], dtype=float)
                vol = float(np.std(recent) * np.sqrt(252))
                if vol > 0:
                    scalar = target_vol / vol
                scalar = float(np.clip(scalar, floor, cap))
        
        w_out = w_in * scalar
        trigger = bool(scalar < 0.999)
        info: Dict[str, Any] = {"target_vol": target_vol, "lookback": lookback, "floor": floor, "cap": cap, "scalar": scalar}
        return OverlayResult("volatility_targeting", w_out, scalar, trigger, info)
'''

# 3. risk_manager_adapter.py
RISK_MANAGER_ADAPTER = '''# Auto-generated by autogen_p0_overlay_bundle.py

from __future__ import annotations

import sys
from typing import Any, Dict

import numpy as np

sys.path.insert(0, "/home/ubuntu/AUB/platform/ares_ultimate_v4_0/src/ares_ultimate/risk")

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult, safe_scalar


class RiskManagerAdapter(BaseAdapter):
    """
    Risk Manager Adapter (CVaR 기반)
    실제 모듈: /home/ubuntu/AUB/platform/ares_ultimate_v4_0/src/ares_ultimate/risk/risk_manager.py
    """
    
    def __init__(self, cfg: Dict[str, Any]):
        super().__init__(cfg)
        self._tail_risk_mgr = None
        self._initialized = False
    
    def _init_module(self):
        if self._initialized:
            return
        try:
            from risk_manager import TailRiskManager, RiskConfig
            
            config = RiskConfig(
                var_confidence=float(self.params.get("var_confidence", 0.95)),
                var_limit=float(self.params.get("var_limit", -0.05)),
                cvar_limit=float(self.params.get("cvar_limit", -0.08)),
            )
            self._tail_risk_mgr = TailRiskManager(config)
            self._initialized = True
        except Exception as e:
            print(f"[WARN] TailRiskManager init failed: {e}")
            self._tail_risk_mgr = None
            self._initialized = True
    
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()
        
        self._init_module()
        
        cvar_alpha = float(self.params.get("cvar_alpha", 0.05))
        scalar = 1.0
        
        if self._tail_risk_mgr is not None and ctx.returns_history is not None:
            try:
                # 실제 모듈 호출
                returns = np.asarray(ctx.returns_history, dtype=float)
                scalar = self._tail_risk_mgr.check_risk(returns)
                scalar = float(np.clip(scalar, 0.0, 1.0))
            except Exception as e:
                print(f"[WARN] TailRiskManager.check_risk failed: {e}")
        
        # Fallback: gross exposure cap 1.0로 정규화
        gross = float(np.sum(np.abs(w_out)))
        if gross > 1.0 and gross > 0:
            w_out = w_out / gross
        
        # 리스크 스케일 적용
        w_out = w_out * scalar
        
        scalar_final = safe_scalar(w_in, w_out)
        trigger = bool(scalar_final < 0.999)
        info: Dict[str, Any] = {"cvar_alpha": cvar_alpha, "risk_scalar": scalar}
        return OverlayResult("risk_manager", w_out, scalar_final, trigger, info)
'''

# 4. regime_detector_adapter.py
REGIME_DETECTOR_ADAPTER = '''# Auto-generated by autogen_p0_overlay_bundle.py

from __future__ import annotations

import sys
from typing import Any, Dict

import numpy as np

sys.path.insert(0, "/home/ubuntu/AUB/baseline")

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult


class RegimeDetectorAdapter(BaseAdapter):
    """
    Regime Detector Adapter
    실제 모듈: /home/ubuntu/AUB/baseline/regime15_adapter.py
    """
    
    def __init__(self, cfg: Dict[str, Any]):
        super().__init__(cfg)
        self._adapter = None
        self._initialized = False
    
    def _init_module(self):
        if self._initialized:
            return
        try:
            from regime15_adapter import Regime15Adapter, Regime15Config
            
            config = Regime15Config(
                enable_regime15=True,
                band_mult_risk_on=float(self.params.get("band_mult_risk_on", 1.0)),
                band_mult_risk_off=float(self.params.get("band_mult_risk_off", 0.5)),
                band_mult_crisis=float(self.params.get("band_mult_crisis", 0.3)),
            )
            self._adapter = Regime15Adapter(config)
            self._initialized = True
        except Exception as e:
            print(f"[WARN] Regime15Adapter init failed: {e}")
            self._adapter = None
            self._initialized = True
    
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        
        self._init_module()
        
        n_states = int(self.params.get("n_states", 4))
        lookback = int(self.params.get("lookback", 252))
        
        scalar = 1.0
        regime = "UNKNOWN"
        
        if self._adapter is not None:
            try:
                # 실제 모듈 호출
                if ctx.timestamp:
                    self._adapter.pre_rebalance(str(ctx.timestamp))
                scalar = self._adapter.get_band_multiplier()
                diag = self._adapter.get_diagnostics()
                regime = diag.get("overall_regime", "UNKNOWN")
            except Exception as e:
                print(f"[WARN] Regime15Adapter failed: {e}")
                # Fallback: VIX 기반 간이 레짐
                vix = ctx.vix
                if vix is not None:
                    if vix >= 35:
                        scalar, regime = 0.1, "CRISIS"
                    elif vix >= 25:
                        scalar, regime = 0.3, "HIGH_VOL"
                    elif vix >= 20:
                        scalar, regime = 0.7, "NORMAL"
                    else:
                        scalar, regime = 1.0, "LOW_VOL"
        else:
            # Fallback: VIX 기반 간이 레짐
            vix = ctx.vix
            if vix is not None:
                if vix >= 35:
                    scalar, regime = 0.1, "CRISIS"
                elif vix >= 25:
                    scalar, regime = 0.3, "HIGH_VOL"
                elif vix >= 20:
                    scalar, regime = 0.7, "NORMAL"
                else:
                    scalar, regime = 1.0, "LOW_VOL"
        
        w_out = w_in * float(scalar)
        trigger = bool(float(scalar) < 0.999)
        info: Dict[str, Any] = {"n_states": n_states, "lookback": lookback, "regime": regime, "scalar": float(scalar)}
        return OverlayResult("regime_detector", w_out, float(scalar), trigger, info)
'''

# 5. market_guard_ml9_adapter.py
MARKET_GUARD_ML9_ADAPTER = '''# Auto-generated by autogen_p0_overlay_bundle.py

from __future__ import annotations

import sys
from typing import Any, Dict

import numpy as np

sys.path.insert(0, "/home/ubuntu/AUB/production_modules")

from ._base import BaseAdapter
from ..p0_pipeline import OverlayContext, OverlayResult


class MarketGuardML9Adapter(BaseAdapter):
    """
    Market Guard ML9 Adapter (Crash Protection)
    실제 모듈: /home/ubuntu/AUB/production_modules/crash_protection_barrier_v1.py
    """
    
    def __init__(self, cfg: Dict[str, Any]):
        super().__init__(cfg)
        self._barrier = None
        self._initialized = False
    
    def _init_module(self):
        if self._initialized:
            return
        try:
            from crash_protection_barrier_v1 import CrashProtectionBarrier, CrashConfig
            
            config = CrashConfig(
                var_confidence=float(self.params.get("var_confidence", 0.95)),
                threshold_crash=float(self.params.get("crash_sigma", 4.0)) / 4.0,  # sigma to threshold
            )
            self._barrier = CrashProtectionBarrier(config)
            self._initialized = True
        except Exception as e:
            print(f"[WARN] CrashProtectionBarrier init failed: {e}")
            self._barrier = None
            self._initialized = True
    
    def apply(self, ctx: OverlayContext, weights: np.ndarray) -> OverlayResult:
        w_in = np.asarray(weights, dtype=float)
        w_out = w_in.copy()
        
        self._init_module()
        
        crash_sigma = float(self.params.get("crash_sigma", 4.0))
        crash = False
        scalar = 1.0
        
        if self._barrier is not None and ctx.returns_history is not None:
            try:
                # 실제 모듈 호출
                returns = np.asarray(ctx.returns_history, dtype=float)
                current_ret = ctx.current_return or 0.0
                vix = ctx.vix or 20.0
                
                result = self._barrier.evaluate(
                    returns=returns,
                    current_return=current_ret,
                    vix=vix,
                    date=str(ctx.timestamp) if ctx.timestamp else None
                )
                
                scalar = result.get("scale", 1.0)
                crash = result.get("crash_level", 0) >= 4  # CRASH level
                
                if crash:
                    w_out[:] = 0.0
                else:
                    w_out = w_in * scalar
            except Exception as e:
                print(f"[WARN] CrashProtectionBarrier.evaluate failed: {e}")
                # Fallback: 간이 급락 감지
                r = ctx.current_return
                if r is not None and r < -0.05:
                    crash = True
                    w_out[:] = 0.0
        else:
            # Fallback: 간이 급락 감지
            r = ctx.current_return
            if r is not None and r < -0.05:
                crash = True
                w_out[:] = 0.0
        
        scalar_final = 0.0 if crash else scalar
        trigger = bool(crash or scalar < 0.999)
        info: Dict[str, Any] = {"crash_sigma": crash_sigma, "crash": crash, "scale": scalar}
        return OverlayResult("market_guard_ml9", w_out, float(scalar_final), trigger, info)
'''


def main():
    """어댑터 파일 업데이트"""
    adapters = {
        "dynamic_no_trade_band_adapter.py": DYNAMIC_NO_TRADE_BAND_ADAPTER,
        "volatility_targeting_adapter.py": VOLATILITY_TARGETING_ADAPTER,
        "risk_manager_adapter.py": RISK_MANAGER_ADAPTER,
        "regime_detector_adapter.py": REGIME_DETECTOR_ADAPTER,
        "market_guard_ml9_adapter.py": MARKET_GUARD_ML9_ADAPTER,
    }
    
    for filename, content in adapters.items():
        path = ADAPTERS_DIR / filename
        path.write_text(content, encoding="utf-8")
        print(f"[OK] Updated: {path}")
    
    print("\n[DONE] All adapters connected to real modules")


if __name__ == "__main__":
    main()
